package com.netmaster.nmx.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@ConditionalOnProperty(name = "nmx.runtime.schema-sync.enabled", havingValue = "true")
@RequiredArgsConstructor
@Slf4j
public class AcsSchemaInitializer implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(String... args) {
        apply("""
                CREATE TABLE IF NOT EXISTS acs_devices (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    acs_device_id VARCHAR(255),
                    ip_address VARCHAR(15),
                    mac_address VARCHAR(17),
                    device_type VARCHAR(50),
                    vendor VARCHAR(50),
                    model VARCHAR(50),
                    serial_number VARCHAR(50),
                    firmware_version VARCHAR(50),
                    software_version VARCHAR(50),
                    olt_id BIGINT,
                    olt_port INTEGER,
                    onu_id INTEGER,
                    optical_rx_power DOUBLE PRECISION,
                    optical_tx_power DOUBLE PRECISION,
                    optical_temperature DOUBLE PRECISION,
                    optical_voltage DOUBLE PRECISION,
                    wifi_name VARCHAR(100),
                    status VARCHAR(20) DEFAULT 'offline',
                    connection_type VARCHAR(20),
                    distance INTEGER,
                    last_acs_request TIMESTAMP,
                    last_inform TIMESTAMP,
                    is_provisioned BOOLEAN DEFAULT FALSE,
                    is_active BOOLEAN DEFAULT TRUE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    last_synced_at TIMESTAMP
                )
                """);
        apply("""
                CREATE TABLE IF NOT EXISTS acs_settings (
                    id BIGINT PRIMARY KEY,
                    server_url VARCHAR(255),
                    username VARCHAR(120),
                    password VARCHAR(255),
                    is_active BOOLEAN DEFAULT TRUE,
                    last_connection_status VARCHAR(30),
                    last_connection_message TEXT,
                    last_connected_at TIMESTAMP,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """);
        apply("ALTER TABLE IF EXISTS acs_devices ADD COLUMN IF NOT EXISTS acs_device_id VARCHAR(255)");
        apply("ALTER TABLE IF EXISTS acs_devices ADD COLUMN IF NOT EXISTS wifi_name VARCHAR(100)");
        apply("ALTER TABLE IF EXISTS acs_devices ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMP");
        apply("CREATE UNIQUE INDEX IF NOT EXISTS idx_acs_devices_acs_device_id ON acs_devices(acs_device_id)");

        apply("""
                INSERT INTO acs_settings (id, is_active, created_at, updated_at)
                VALUES (1, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                ON CONFLICT (id) DO NOTHING
                """);
    }

    private void apply(String sql) {
        try {
            jdbcTemplate.execute(sql);
        } catch (Exception ex) {
            log.warn("Skipping ACS schema sync for SQL [{}]: {}", sql, ex.getMessage());
        }
    }
}
