package com.netmaster.nmx.config;

import com.netmaster.nmx.model.Role;
import com.netmaster.nmx.model.User;
import com.netmaster.nmx.repository.RoleRepository;
import com.netmaster.nmx.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.core.annotation.Order;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.util.HashSet;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

@Component
@RequiredArgsConstructor
@Slf4j
@ConditionalOnProperty(name = "nmx.runtime.schema-sync.enabled", havingValue = "true")
@Order(20)
public class DataInitializer implements CommandLineRunner {

    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final PasswordEncoder passwordEncoder;
    private final JdbcTemplate jdbcTemplate;
    
    @Value("${nmx.bootstrap.seed-default-users:false}")
    private boolean seedDefaultUsers;

    @Value("${nmx.bootstrap.default-password:Domboot007@@@}")
    private String defaultPassword;

    @Override
    public void run(String... args) {
        if (!seedDefaultUsers) {
            log.info("Default role/user bootstrap is disabled. Set nmx.bootstrap.seed-default-users=true to enable it.");
            return;
        }

        ensureSecuritySchema();
        if (!isSecuritySchemaReady()) {
            log.warn("Skipping default role/user bootstrap because security schema is not ready yet.");
            return;
        }

        try {
            initializeRoles();
            initializeSuperAdmin();
        } catch (DataAccessException ex) {
            log.warn("Skipping default role/user bootstrap because security schema access failed: {}", ex.getMessage());
        }
    }

    private void ensureSecuritySchema() {
        apply("""
                CREATE TABLE IF NOT EXISTS roles (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(50) NOT NULL UNIQUE,
                    description TEXT,
                    permissions_level VARCHAR(20) NOT NULL DEFAULT 'READ'
                )
                """);
        apply("""
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    employee_id VARCHAR(50),
                    full_name VARCHAR(150),
                    username VARCHAR(100) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    email VARCHAR(150),
                    phone VARCHAR(30),
                    is_active BOOLEAN NOT NULL DEFAULT TRUE
                )
                """);
        apply("""
                CREATE TABLE IF NOT EXISTS user_roles (
                    user_id BIGINT NOT NULL,
                    role_id BIGINT NOT NULL,
                    PRIMARY KEY (user_id, role_id)
                )
                """);
    }

    private void apply(String sql) {
        try {
            jdbcTemplate.execute(sql);
        } catch (Exception ex) {
            log.warn("Security bootstrap skipped for SQL [{}]: {}", sql, ex.getMessage());
        }
    }

    private boolean isSecuritySchemaReady() {
        try {
            Integer roles = jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM information_schema.tables WHERE lower(table_name) = 'roles'",
                    Integer.class
            );
            Integer users = jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM information_schema.tables WHERE lower(table_name) = 'users'",
                    Integer.class
            );
            Integer userRoles = jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM information_schema.tables WHERE lower(table_name) = 'user_roles'",
                    Integer.class
            );
            return roles != null && roles > 0
                    && users != null && users > 0
                    && userRoles != null && userRoles > 0;
        } catch (DataAccessException ex) {
            log.warn("Unable to verify security schema readiness: {}", ex.getMessage());
            return false;
        }
    }

    private void initializeRoles() {
        // Create ROLE_SUPER_ADMIN role
        if (roleRepository.findByName("ROLE_SUPER_ADMIN").isEmpty()) {
            Role superAdminRole = new Role();
            superAdminRole.setName("ROLE_SUPER_ADMIN");
            superAdminRole.setDescription("Super Administrator - Full CRUD Access");
            superAdminRole.setPermissionsLevel("FULL");
            roleRepository.save(superAdminRole);
            log.info("Created role: ROLE_SUPER_ADMIN");
        }

        // Create ROLE_ADMIN role
        if (roleRepository.findByName("ROLE_ADMIN").isEmpty()) {
            Role adminRole = new Role();
            adminRole.setName("ROLE_ADMIN");
            adminRole.setDescription("Administrator - Create, Read, Update, Delete");
            adminRole.setPermissionsLevel("WRITE");
            roleRepository.save(adminRole);
            log.info("Created role: ROLE_ADMIN");
        }

        // Create ROLE_SIDE_ADMIN role
        if (roleRepository.findByName("ROLE_SIDE_ADMIN").isEmpty()) {
            Role sideAdminRole = new Role();
            sideAdminRole.setName("ROLE_SIDE_ADMIN");
            sideAdminRole.setDescription("Side Admin - Create and Read only");
            sideAdminRole.setPermissionsLevel("READ");
            roleRepository.save(sideAdminRole);
            log.info("Created role: ROLE_SIDE_ADMIN");
        }
        
        // Create ROLE_TECHNICIAN role
        if (roleRepository.findByName("ROLE_TECHNICIAN").isEmpty()) {
            Role technicianRole = new Role();
            technicianRole.setName("ROLE_TECHNICIAN");
            technicianRole.setDescription("Technician - Limited Access");
            technicianRole.setPermissionsLevel("READ");
            roleRepository.save(technicianRole);
            log.info("Created role: ROLE_TECHNICIAN");
        }
        
        // Create ROLE_FINANCE role
        if (roleRepository.findByName("ROLE_FINANCE").isEmpty()) {
            Role financeRole = new Role();
            financeRole.setName("ROLE_FINANCE");
            financeRole.setDescription("Finance - Billing Access");
            financeRole.setPermissionsLevel("READ");
            roleRepository.save(financeRole);
            log.info("Created role: ROLE_FINANCE");
        }
    }

    private void initializeSuperAdmin() {
        // Create Super Admin user (netmaster - NMX-001)
        Optional<User> existingSuperAdmin = userRepository.findByUsername("netmaster");
        if (existingSuperAdmin.isEmpty()) {
            User superAdmin = new User();
            superAdmin.setEmployeeId("NMX-001");
            superAdmin.setFullName("superadmin");
            superAdmin.setUsername("netmaster");
            superAdmin.setPassword(resolveBootstrapPasswordHash());
            superAdmin.setEmail("netmaster.idn@gmail.com");
            superAdmin.setPhone("08158077992");
            superAdmin.setActive(true);
            
            Set<Role> superAdminRoles = new HashSet<>();
            roleRepository.findByName("ROLE_SUPER_ADMIN").ifPresent(superAdminRoles::add);
            superAdmin.setRoles(superAdminRoles);
            
            userRepository.save(superAdmin);
            log.info("Created bootstrap user: netmaster (NMX-001)");
        } else {
            // Update user if exists
            User superAdmin = existingSuperAdmin.get();
            superAdmin.setEmployeeId("NMX-001");
            superAdmin.setFullName("superadmin");
            superAdmin.setPassword(resolveBootstrapPasswordHash());
            superAdmin.setEmail("netmaster.idn@gmail.com");
            superAdmin.setPhone("08158077992");
            superAdmin.setActive(true);
            
            Set<Role> superAdminRoles = new HashSet<>();
            roleRepository.findByName("ROLE_SUPER_ADMIN").ifPresent(superAdminRoles::add);
            superAdmin.setRoles(superAdminRoles);
            
            userRepository.save(superAdmin);
            log.info("Updated bootstrap user: netmaster (NMX-001)");
        }
    }

    private String resolveBootstrapPasswordHash() {
        String rawPassword = sanitizeBootstrapPassword(Objects.requireNonNullElse(defaultPassword, "Domboot007@@@"));
        if (rawPassword.isEmpty()) {
            rawPassword = "Domboot007@@@";
        }
        return passwordEncoder.encode(rawPassword);
    }

    private String sanitizeBootstrapPassword(String value) {
        if (value == null) {
            return "";
        }

        String sanitized = value.trim();
        if (sanitized.length() >= 2) {
            boolean wrappedInDoubleQuotes = sanitized.startsWith("\"") && sanitized.endsWith("\"");
            boolean wrappedInSingleQuotes = sanitized.startsWith("'") && sanitized.endsWith("'");
            if (wrappedInDoubleQuotes || wrappedInSingleQuotes) {
                sanitized = sanitized.substring(1, sanitized.length() - 1).trim();
            }
        }
        return sanitized;
    }
}
