package com.netmaster.nmx.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Locale;
import java.util.Set;
import java.util.stream.Collectors;

@Component
@RequiredArgsConstructor
@Slf4j
public class MasterDataInitializer implements CommandLineRunner {

    @Qualifier("masterJdbcTemplate")
    private final JdbcTemplate masterJdbcTemplate;
    private final PasswordEncoder passwordEncoder;

    @Value("${nmx.bootstrap.seed-default-users:false}")
    private boolean seedDefaultUsers;

    @Value("${nmx.bootstrap.default-password:Domboot007@@@}")
    private String defaultPassword;

    @Override
    @Transactional("masterTransactionManager")
    public void run(String... args) {
        ensureCoreTables();
        ensureTrialPlan();
        if (seedDefaultUsers) {
            ensureMasterSuperAdmin();
        }
    }

    private void ensureCoreTables() {
        masterJdbcTemplate.execute("""
                create table if not exists isp_registrations (
                    id bigint generated by default as identity primary key,
                    company_name varchar(150) not null,
                    slug varchar(100) not null unique,
                    email varchar(150) not null unique,
                    phone varchar(30) not null,
                    address text,
                    owner_name varchar(150) not null,
                    owner_email varchar(150) not null,
                    owner_username varchar(100) not null,
                    owner_password_hash varchar(255) not null,
                    status varchar(20) not null,
                    requested_plan_code varchar(50),
                    rejection_reason text,
                    reviewed_by bigint,
                    reviewed_at timestamp null,
                    created_at timestamp not null default current_timestamp,
                    updated_at timestamp not null default current_timestamp
                )
                """);
        masterJdbcTemplate.execute("""
                create table if not exists subscription_plans (
                    id bigint generated by default as identity primary key,
                    code varchar(50) not null unique,
                    name varchar(100) not null,
                    price_monthly decimal(12,2),
                    max_users integer,
                    max_customers integer,
                    is_active boolean not null default true,
                    features_json text,
                    created_at timestamp not null default current_timestamp,
                    updated_at timestamp not null default current_timestamp
                )
                """);
        masterJdbcTemplate.execute("""
                create table if not exists superadmins (
                    id bigint generated by default as identity primary key,
                    username varchar(150) not null unique,
                    email varchar(150) not null unique,
                    full_name varchar(150) not null,
                    password_hash varchar(255) not null,
                    is_active boolean not null default true,
                    last_login_at timestamp null,
                    created_at timestamp not null default current_timestamp,
                    updated_at timestamp not null default current_timestamp
                )
                """);
        masterJdbcTemplate.execute("""
                create table if not exists tenants (
                    id bigint generated by default as identity primary key,
                    company_name varchar(150) not null,
                    slug varchar(100) not null unique,
                    email varchar(150) not null unique,
                    phone varchar(30),
                    address text,
                    db_name varchar(120),
                    db_host varchar(120),
                    db_user varchar(120),
                    db_password varchar(500),
                    status varchar(20) not null,
                    approved_by bigint,
                    approved_at timestamp null,
                    subscription_starts_at date,
                    subscription_ends_at date,
                    subscription_plan_id bigint,
                    registration_id bigint,
                    created_at timestamp not null default current_timestamp,
                    updated_at timestamp not null default current_timestamp,
                    deleted_at timestamp null
                )
                """);
        masterJdbcTemplate.execute("""
                create table if not exists tenant_databases (
                    id bigint generated by default as identity primary key,
                    tenant_id bigint not null unique,
                    db_name varchar(120) not null unique,
                    db_host varchar(120) not null,
                    db_port integer not null,
                    db_user varchar(120) not null,
                    db_password_encrypted varchar(500) not null,
                    jdbc_url varchar(500) not null,
                    is_active boolean not null default true,
                    created_at timestamp not null default current_timestamp,
                    updated_at timestamp not null default current_timestamp
                )
                """);
        masterJdbcTemplate.execute("""
                create table if not exists tenant_users_index (
                    id bigint generated by default as identity primary key,
                    tenant_id bigint not null,
                    user_id_in_tenant_db bigint not null,
                    email varchar(150) not null,
                    username varchar(100) not null,
                    role varchar(50) not null,
                    status varchar(20) not null,
                    created_at timestamp not null default current_timestamp
                )
                """);
        masterJdbcTemplate.execute("""
                create table if not exists audit_logs (
                    id bigint generated by default as identity primary key,
                    actor_type varchar(50) not null,
                    actor_id bigint,
                    action varchar(150) not null,
                    tenant_id bigint,
                    target_type varchar(100),
                    target_id varchar(100),
                    metadata_json text,
                    request_ip varchar(100),
                    created_at timestamp not null default current_timestamp
                )
                """);
        masterJdbcTemplate.execute("""
                create table if not exists activity_logs (
                    id bigint generated by default as identity primary key,
                    tenant_id bigint,
                    activity text not null,
                    created_at timestamp not null default current_timestamp
                )
                """);
        masterJdbcTemplate.execute("""
                create table if not exists approval_history (
                    id bigint generated by default as identity primary key,
                    registration_id bigint,
                    tenant_id bigint,
                    action varchar(30) not null,
                    actor_id bigint,
                    actor_type varchar(50) not null,
                    notes text,
                    created_at timestamp not null default current_timestamp
                )
                """);
        ensureMasterSchemaColumns();
    }

    private void ensureMasterSchemaColumns() {
        Set<String> tenantColumns = getExistingColumns("tenants");
        ensureColumn("tenants", tenantColumns, "company_name", "varchar(150) not null");
        ensureColumn("tenants", tenantColumns, "slug", "varchar(100)");
        ensureColumn("tenants", tenantColumns, "email", "varchar(150)");
        ensureColumn("tenants", tenantColumns, "phone", "varchar(30)");
        ensureColumn("tenants", tenantColumns, "address", "text");
        ensureColumn("tenants", tenantColumns, "db_name", "varchar(120)");
        ensureColumn("tenants", tenantColumns, "db_host", "varchar(120)");
        ensureColumn("tenants", tenantColumns, "db_user", "varchar(120)");
        ensureColumn("tenants", tenantColumns, "db_password", "varchar(500)");
        ensureColumn("tenants", tenantColumns, "status", "varchar(20) not null default 'PENDING'");
        ensureColumn("tenants", tenantColumns, "approved_by", "bigint");
        ensureColumn("tenants", tenantColumns, "approved_at", "timestamp null");
        ensureColumn("tenants", tenantColumns, "subscription_starts_at", "date");
        ensureColumn("tenants", tenantColumns, "subscription_ends_at", "date");
        ensureColumn("tenants", tenantColumns, "subscription_plan_id", "bigint");
        ensureColumn("tenants", tenantColumns, "registration_id", "bigint");
        ensureColumn("tenants", tenantColumns, "created_at", "timestamp not null default current_timestamp");
        ensureColumn("tenants", tenantColumns, "updated_at", "timestamp not null default current_timestamp");
        ensureColumn("tenants", tenantColumns, "deleted_at", "timestamp null");
    }

    private Set<String> getExistingColumns(String tableName) {
        return masterJdbcTemplate.query(
                        """
                        select column_name
                        from information_schema.columns
                        where lower(table_name) = lower(?)
                        """,
                        new ColumnNameMapper(),
                        tableName
                ).stream()
                .map(value -> value.toLowerCase(Locale.ROOT))
                .collect(Collectors.toSet());
    }

    private void ensureColumn(String tableName, Set<String> existingColumns, String columnName, String columnDefinition) {
        if (existingColumns.contains(columnName.toLowerCase(Locale.ROOT))) {
            return;
        }
        masterJdbcTemplate.execute("alter table " + tableName + " add column " + columnName + " " + columnDefinition);
        existingColumns.add(columnName.toLowerCase(Locale.ROOT));
    }

    private static class ColumnNameMapper implements RowMapper<String> {
        @Override
        public String mapRow(ResultSet rs, int rowNum) throws SQLException {
            return rs.getString("column_name");
        }
    }

    private void ensureTrialPlan() {
        Integer existing = masterJdbcTemplate.queryForObject(
                "select count(*) from subscription_plans where code = ?",
                Integer.class,
                "TRIAL"
        );
        if (existing != null && existing > 0) {
            return;
        }
        masterJdbcTemplate.update(
                """
                insert into subscription_plans
                (code, name, price_monthly, max_users, max_customers, is_active, created_at, updated_at)
                values (?, ?, ?, ?, ?, ?, current_timestamp, current_timestamp)
                """,
                "TRIAL",
                "Trial Plan",
                BigDecimal.ZERO,
                5,
                100,
                true
        );
    }

    private void ensureMasterSuperAdmin() {
        Integer existing = masterJdbcTemplate.queryForObject(
                "select count(*) from superadmins where username = ?",
                Integer.class,
                "netmaster"
        );
        String passwordHash = passwordEncoder.encode(defaultPassword);
        if (existing != null && existing > 0) {
            masterJdbcTemplate.update(
                    """
                    update superadmins
                    set email = ?, full_name = ?, password_hash = ?, is_active = ?, updated_at = current_timestamp
                    where username = ?
                    """,
                    "netmaster.idn@gmail.com",
                    "superadmin",
                    passwordHash,
                    true,
                    "netmaster"
            );
        } else {
            masterJdbcTemplate.update(
                    """
                    insert into superadmins
                    (username, email, full_name, password_hash, is_active, created_at, updated_at)
                    values (?, ?, ?, ?, ?, current_timestamp, current_timestamp)
                    """,
                    "netmaster",
                    "netmaster.idn@gmail.com",
                    "superadmin",
                    passwordHash,
                    true
            );
        }
        log.info("Master superadmin ensured for SaaS control plane.");
    }
}
