package com.netmaster.nmx.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@ConditionalOnProperty(name = "nmx.runtime.schema-sync.enabled", havingValue = "true")
@RequiredArgsConstructor
@Slf4j
@Order(10)
public class SecuritySchemaInitializer implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(String... args) {
        apply("""
                CREATE TABLE IF NOT EXISTS roles (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(50) NOT NULL UNIQUE,
                    description TEXT,
                    permissions_level VARCHAR(20) NOT NULL DEFAULT 'READ'
                )
                """);
        apply("""
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    employee_id VARCHAR(50),
                    full_name VARCHAR(150),
                    username VARCHAR(100) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    email VARCHAR(150),
                    phone VARCHAR(30),
                    is_active BOOLEAN NOT NULL DEFAULT TRUE
                )
                """);
        apply("""
                CREATE TABLE IF NOT EXISTS user_roles (
                    user_id BIGINT NOT NULL,
                    role_id BIGINT NOT NULL,
                    PRIMARY KEY (user_id, role_id)
                )
                """);
        apply("ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS user_id BIGINT");
        apply("ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS role_id BIGINT");
    }

    private void apply(String sql) {
        try {
            jdbcTemplate.execute(sql);
        } catch (Exception ex) {
            log.warn("Skipping security schema sync for SQL [{}]: {}", sql, ex.getMessage());
        }
    }
}
