CREATE TABLE IF NOT EXISTS servers (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    ip_address VARCHAR(15) NOT NULL,
    location VARCHAR(255),
    mikrotik_id BIGINT,
    region_id BIGINT,
    latitude NUMERIC(10,8),
    longitude NUMERIC(11,8),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS olt_devices (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    ip_address VARCHAR(45),
    vpn_ip_address VARCHAR(45),
    username VARCHAR(50),
    password VARCHAR(100),
    vendor VARCHAR(50),
    model VARCHAR(50),
    serial_number VARCHAR(50),
    slot_count INTEGER,
    pon_port_count INTEGER,
    gpon_port_count INTEGER,
    location VARCHAR(200),
    description VARCHAR(500),
    status VARCHAR(20) DEFAULT 'offline',
    onu_count INTEGER,
    optical_rx_power DOUBLE PRECISION,
    optical_tx_power DOUBLE PRECISION,
    temperature DOUBLE PRECISION,
    voltage DOUBLE PRECISION,
    last_monitored TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS odcs
    ADD COLUMN IF NOT EXISTS server_id BIGINT;

ALTER TABLE IF EXISTS odcs
    ADD COLUMN IF NOT EXISTS location VARCHAR(255);

ALTER TABLE IF EXISTS odcs
    ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,8);

ALTER TABLE IF EXISTS odcs
    ADD COLUMN IF NOT EXISTS longitude NUMERIC(11,8);

ALTER TABLE IF EXISTS odcs
    ADD COLUMN IF NOT EXISTS capacity INTEGER DEFAULT 32;

ALTER TABLE IF EXISTS odcs
    ADD COLUMN IF NOT EXISTS used_port INTEGER DEFAULT 0;

ALTER TABLE IF EXISTS odcs
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE IF EXISTS odps
    ADD COLUMN IF NOT EXISTS odc_id BIGINT;

ALTER TABLE IF EXISTS odps
    ADD COLUMN IF NOT EXISTS company_profile_id BIGINT;

ALTER TABLE IF EXISTS odps
    ADD COLUMN IF NOT EXISTS node_type VARCHAR(10) DEFAULT 'ODP';

ALTER TABLE IF EXISTS odps
    ADD COLUMN IF NOT EXISTS location VARCHAR(255);

ALTER TABLE IF EXISTS odps
    ADD COLUMN IF NOT EXISTS splitter VARCHAR(100);

ALTER TABLE IF EXISTS odps
    ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,8);

ALTER TABLE IF EXISTS odps
    ADD COLUMN IF NOT EXISTS longitude NUMERIC(11,8);

ALTER TABLE IF EXISTS odps
    ADD COLUMN IF NOT EXISTS capacity INTEGER DEFAULT 8;

ALTER TABLE IF EXISTS odps
    ADD COLUMN IF NOT EXISTS used_port INTEGER DEFAULT 0;

ALTER TABLE IF EXISTS odps
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
