ALTER TABLE IF EXISTS internet_packages
    ADD COLUMN IF NOT EXISTS burst_download INTEGER;

ALTER TABLE IF EXISTS internet_packages
    ADD COLUMN IF NOT EXISTS burst_upload INTEGER;

ALTER TABLE IF EXISTS internet_packages
    ADD COLUMN IF NOT EXISTS mikrotik_profile_name VARCHAR(100);

ALTER TABLE IF EXISTS internet_packages
    ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE IF EXISTS internet_packages
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE IF EXISTS internet_packages
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS internet_packages
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
